//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departman
    {
        public Departman()
        {
            this.Doktor = new HashSet<Doktor>();
            this.Pacijent = new HashSet<Pacijent>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Sprat { get; set; }
    
        public virtual Klinika Klinika { get; set; }
        public virtual ICollection<Doktor> Doktor { get; set; }
        public virtual ICollection<Pacijent> Pacijent { get; set; }
    }
}
