//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktor : Korisnik
    {
        public Doktor()
        {
            this.Pregleds = new HashSet<Pregled>();
            this.Pregled_Specijaliste = new HashSet<Pregled_Specijaliste>();
            this.Dodatni_Pregled = new HashSet<Pregled_Specijaliste>();
        }
    
        public string Specijalizacija { get; set; }
    
        public virtual Departman Departmen { get; set; }
        public virtual ICollection<Pregled> Pregleds { get; set; }
        public virtual ICollection<Pregled_Specijaliste> Pregled_Specijaliste { get; set; }
        public virtual ICollection<Pregled_Specijaliste> Dodatni_Pregled { get; set; }
    }
}
