//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klinika
    {
        public Klinika()
        {
            this.Departmen = new HashSet<Departman>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Departman> Departmen { get; set; }
    }
}
