//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Korisnicko_Ime { get; set; }
        public string Lozinka { get; set; }
        public string Uloga { get; set; }
        public string Kontakt { get; set; }
        public string Email { get; set; }
        public string Ulica { get; set; }
        public string Grad { get; set; }
        public string Broj { get; set; }
    }
}
