//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregled_Specijaliste
    {
        public int Id { get; set; }
    
        public virtual Uput Uput { get; set; }
        public virtual Doktor Doktor_Specijalista { get; set; }
        public virtual Doktor Doktor_Opste_Prakse { get; set; }
        public virtual Pacijent Pacijent { get; set; }
        public virtual Ishod_Pregleda Ishod_Pregleda { get; set; }
        public virtual Termin_Specijaliste Termin_Specijaliste { get; set; }
    }
}
