//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termin
    {
        public Termin()
        {
            this.Pregled = new HashSet<Pregled>();
        }
    
        public int Id { get; set; }
        public string Datum { get; set; }
        public string Vreme { get; set; }
    
        public virtual ICollection<Pregled> Pregled { get; set; }
    }
}
