//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uput : Ishod_Pregleda
    {
        public Uput()
        {
            this.Pregled_Specijaliste = new HashSet<Pregled_Specijaliste>();
        }
    
    
        public virtual ICollection<Pregled_Specijaliste> Pregled_Specijaliste { get; set; }
    }
}
